resources:
- ../../base
namePrefix: staging-
commonLabels:
  env: staging
patchesStrategicMerge:
- staging-configmap.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="Staging"
  name: rsvpconfig-staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: teamcloudyuga/rsvpapp
  newName: vijaymodi9/rsvp
  newTag: cd40359ab211ca23ace43fff814412c1f0b7f939
